In [1]:
!pip3 install fredapi

Collecting fredapi
  Using cached fredapi-0.5.0-py3-none-any.whl (11 kB)
Requirement already satisfied: pandas in ./lib/python3.9/site-packages (from fredapi) (1.4.1)
Requirement already satisfied: pytz>=2020.1 in ./lib/python3.9/site-packages (from pandas->fredapi) (2021.3)
Requirement already satisfied: numpy>=1.18.5 in ./lib/python3.9/site-packages (from pandas->fredapi) (1.22.3)
Requirement already satisfied: python-dateutil>=2.8.1 in ./lib/python3.9/site-packages (from pandas->fredapi) (2.8.2)
Requirement already satisfied: six>=1.5 in ./lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas->fredapi) (1.16.0)
Installing collected packages: fredapi
Successfully installed fredapi-0.5.0

In [8]:
from fredapi import Fred
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from urllib.request import urlopen
import json
# 한글폰트 출력 가능 코드
from matplotlib import rc
rc('font', family='AppleGothic') # Mac Os
#rc('font', family='NanumGothic') # Windows Os
plt.rcParams['axes.unicode_minus'] = False

# FRED api 키 입력 (https://fred.stlouisfed.org)
fred_key='개인 key 입력'

# ECOS API 키 입력 (https://ecos.bok.or.kr/jsp/openapi/OpenApiController.jsp)
ecos_key = '개인 key 입력'

# FRED API

In [15]:
# FRED api 키 입력
fred = Fred(api_key = fred_key)

# S&P 500 불러오기
sp500 = fred.get_series('SP500')
sp500 = pd.DataFrame(sp500, columns=['SP500'])
sp500

              SP500
2012-04-30  1397.91
2012-05-01  1405.82
2012-05-02  1402.31
2012-05-03  1391.57
2012-05-04  1369.10
...             ...
2022-04-21  4393.66
2022-04-22  4271.78
2022-04-25  4296.12
2022-04-26  4175.20
2022-04-27  4183.96

[2608 rows x 1 columns]

In [16]:
# 장단기 금리 차이 (10년, 2년물)
t10y2y = fred.get_series('T10Y2Y', observation_start='4/30/2012', observation_end='4/27/2022')
t10y2y = pd.DataFrame(t10y2y, columns=['t10y2y'])
t10y2y

            t10y2y
2012-04-30    1.68
2012-05-01    1.71
2012-05-02    1.69
2012-05-03    1.68
2012-05-04    1.64
...            ...
2022-04-21    0.22
2022-04-22    0.18
2022-04-25    0.18
2022-04-26    0.23
2022-04-27    0.24

[2608 rows x 1 columns]

# ECOS API

url 지정에 대한 설명 참고 (https://ecos.bok.or.kr/jsp/openapi/OpenApiController.jsp?t=guideServiceDtl&apiCode=OA-1040&menuGroup=MENU000004)

![image](https://user-images.githubusercontent.com/87803612/166404129-0ec3b058-466b-4031-bdf5-cd0077662bea.png)

In [69]:
# url 설정 (설명은 이미지 참고)
url = "http://ecos.bok.or.kr/api/StatisticSearch/" + ecos_key + "/json/kr/1/60/060Y001/DD/20220302/20220502/010200000"


result = urlopen(url)
html = result.read()
data = json.loads(html)

pd.DataFrame(data['StatisticSearch']['row'])

,UNIT_NAME,STAT_NAME,ITEM_CODE1,STAT_CODE,ITEM_CODE2,ITEM_CODE3,ITEM_NAME1,ITEM_NAME2,DATA_VALUE,ITEM_NAME3,TIME
0,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.187,,20220302
1,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.195,,20220303
2,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.214,,20220304
3,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.288,,20220307
4,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.287,,20220308
5,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.267,,20220310
6,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.255,,20220311
7,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.283,,20220314
8,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.285,,20220315
9,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.268,,20220316
10,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.217,,20220317
11,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.231,,20220318
12,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.268,,20220321
13,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.399,,20220322
14,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.426,,20220323
15,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.455,,20220324
16,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.505,,20220325
17,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.747,,20220328
18,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.7,,20220329
19,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.615,,20220330
20,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.663,,20220331
21,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.784,,20220401
22,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.837,,20220404
23,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.879,,20220405
24,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.941,,20220406
25,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.905,,20220407
26,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.987,,20220408
27,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,3.186,,20220411
28,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,3.105,,20220412
29,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,3.001,,20220413
30,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.888,,20220414
31,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.944,,20220415
32,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.99,,20220418
33,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.981,,20220419
34,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.957,,20220420
35,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.927,,20220421
36,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.971,,20220422
37,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.857,,20220425
38,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.83,,20220426
39,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.899,,20220427
40,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.925,,20220428
41,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,2.958,,20220429